CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tenants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS accounts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, password_hash text NOT NULL, platform_role text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS account_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, csrf_token text NOT NULL, ip text, user_agent text, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS account_sessions_account_idx ON account_sessions(account_id);
CREATE TABLE IF NOT EXISTS tenant_members (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE, role text NOT NULL DEFAULT 'viewer', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (tenant_id, account_id));
CREATE TABLE IF NOT EXISTS plans (id text PRIMARY KEY, name text NOT NULL, status text NOT NULL DEFAULT 'active', entitlements jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS subscriptions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, plan_id text NOT NULL REFERENCES plans(id), status text NOT NULL DEFAULT 'trialing', period_start timestamptz, period_end timestamptz, provider text, provider_reference text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS subscriptions_tenant_idx ON subscriptions(tenant_id);
CREATE TABLE IF NOT EXISTS feature_flags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL, scope_type text NOT NULL, scope_id text NOT NULL, enabled boolean NOT NULL DEFAULT false, config jsonb NOT NULL DEFAULT '{}'::jsonb, updated_by uuid REFERENCES accounts(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(key, scope_type, scope_id));
CREATE TABLE IF NOT EXISTS sites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name text NOT NULL, domain text NOT NULL, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id, domain));
CREATE INDEX IF NOT EXISTS sites_tenant_idx ON sites(tenant_id);
CREATE TABLE IF NOT EXISTS site_domains (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE, domain text NOT NULL, verified_at timestamptz, verification_token text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(site_id, domain));
CREATE TABLE IF NOT EXISTS api_keys (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, name text NOT NULL, key_prefix text NOT NULL UNIQUE, secret_hash text NOT NULL, scopes jsonb NOT NULL DEFAULT '[]'::jsonb, last_used_at timestamptz, expires_at timestamptz, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS api_keys_tenant_idx ON api_keys(tenant_id);
CREATE TABLE IF NOT EXISTS assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE, title text NOT NULL, provider text NOT NULL, provider_reference text NOT NULL, allowed_hosts jsonb NOT NULL DEFAULT '[]'::jsonb, encrypted_provider_config text, security_policy text NOT NULL DEFAULT 'strict', status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS assets_tenant_idx ON assets(tenant_id); CREATE INDEX IF NOT EXISTS assets_site_idx ON assets(site_id);
CREATE TABLE IF NOT EXISTS end_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, external_user_id text NOT NULL, display_label text, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id, external_user_id));
CREATE INDEX IF NOT EXISTS end_users_tenant_idx ON end_users(tenant_id);
CREATE TABLE IF NOT EXISTS devices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, end_user_id uuid NOT NULL REFERENCES end_users(id) ON DELETE CASCADE, external_device_id text NOT NULL, device_name text, browser text, os text, status text NOT NULL DEFAULT 'active', first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id, end_user_id, external_device_id));
CREATE INDEX IF NOT EXISTS devices_user_idx ON devices(end_user_id);
CREATE TABLE IF NOT EXISTS playback_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, site_id uuid NOT NULL REFERENCES sites(id) ON DELETE CASCADE, asset_id uuid NOT NULL REFERENCES assets(id) ON DELETE CASCADE, end_user_id uuid NOT NULL REFERENCES end_users(id) ON DELETE CASCADE, device_id uuid NOT NULL REFERENCES devices(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'active', ip text, user_agent text, started_at timestamptz NOT NULL DEFAULT now(), last_heartbeat_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, ended_at timestamptz);
CREATE INDEX IF NOT EXISTS playback_sessions_tenant_idx ON playback_sessions(tenant_id); CREATE INDEX IF NOT EXISTS playback_sessions_user_status_idx ON playback_sessions(end_user_id, status);
CREATE TABLE IF NOT EXISTS security_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, site_id uuid REFERENCES sites(id), end_user_id uuid REFERENCES end_users(id), asset_id uuid REFERENCES assets(id), session_id uuid REFERENCES playback_sessions(id), type text NOT NULL, severity text NOT NULL DEFAULT 'info', risk_score integer NOT NULL DEFAULT 0, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS security_events_tenant_created_idx ON security_events(tenant_id, created_at);
CREATE TABLE IF NOT EXISTS usage_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, type text NOT NULL, quantity integer NOT NULL DEFAULT 1, asset_id uuid REFERENCES assets(id), session_id uuid REFERENCES playback_sessions(id), metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS usage_events_tenant_created_idx ON usage_events(tenant_id, created_at);
CREATE TABLE IF NOT EXISTS usage_rollups (tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, period text NOT NULL, metric text NOT NULL, quantity integer NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id, period, metric));
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid REFERENCES tenants(id), actor_account_id uuid REFERENCES accounts(id), action text NOT NULL, target_type text, target_id text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, ip text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_logs_tenant_created_idx ON audit_logs(tenant_id, created_at);
CREATE TABLE IF NOT EXISTS webhook_endpoints (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, url text NOT NULL, secret_hash text NOT NULL, encrypted_secret text NOT NULL, events jsonb NOT NULL DEFAULT '[]'::jsonb, status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS webhooks_tenant_idx ON webhook_endpoints(tenant_id);
CREATE TABLE IF NOT EXISTS webhook_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), endpoint_id uuid NOT NULL REFERENCES webhook_endpoints(id) ON DELETE CASCADE, event_id text NOT NULL, event_type text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'pending', attempts integer NOT NULL DEFAULT 0, next_attempt_at timestamptz NOT NULL DEFAULT now(), last_error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS webhook_deliveries_pending_idx ON webhook_deliveries(status, next_attempt_at);
CREATE TABLE IF NOT EXISTS provider_health (provider text PRIMARY KEY, status text NOT NULL DEFAULT 'healthy', last_success_at timestamptz, last_failure_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamptz NOT NULL DEFAULT now());

INSERT INTO plans (id, name, status, entitlements) VALUES
('starter','Starter','active','{"secure_gateway":true,"dynamic_watermark":true,"device_control":true,"max_sites":1,"max_devices_per_user":2,"max_concurrent_streams":1,"session_policy":"block_new"}'::jsonb),
('pro','Pro','active','{"secure_gateway":true,"dynamic_watermark":true,"device_control":true,"max_sites":3,"max_devices_per_user":4,"max_concurrent_streams":2,"session_policy":"revoke_old"}'::jsonb),
('business','Business','active','{"secure_gateway":true,"dynamic_watermark":true,"device_control":true,"max_sites":10,"max_devices_per_user":8,"max_concurrent_streams":3,"session_policy":"revoke_old","advanced_security":true}'::jsonb)
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, entitlements=EXCLUDED.entitlements, updated_at=now();
INSERT INTO feature_flags (key,scope_type,scope_id,enabled) VALUES ('secure_gateway','global','global',true),('dynamic_watermark','global','global',true),('device_control','global','global',true),('youtube_custom','global','global',false) ON CONFLICT (key,scope_type,scope_id) DO NOTHING;
INSERT INTO provider_health(provider,status) VALUES ('direct','healthy'),('hls','healthy'),('s3','healthy'),('r2','healthy'),('bunny','healthy'),('youtube_custom','disabled') ON CONFLICT (provider) DO NOTHING;
